# Generated by Django 3.0.8 on 2020-07-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PigIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigid', models.IntegerField(verbose_name='身份码')),
                ('earid', models.IntegerField(verbose_name='耳标号')),
                ('entrytime', models.DateTimeField(verbose_name='开始时间')),
                ('outtime', models.DateTimeField(verbose_name='结束时间')),
                ('feedquantity', models.CharField(default=0, max_length=20, verbose_name='采食量')),
            ],
            options={
                'verbose_name': '母猪采食表',
                'verbose_name_plural': '母猪采食表',
                'db_table': 'tb_pigintake',
            },
        ),
    ]
