# Generated by Django 3.0.8 on 2020-07-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigid', models.IntegerField(verbose_name='身份码')),
                ('earid', models.IntegerField(verbose_name='耳标号')),
                ('backfat', models.CharField(max_length=20, verbose_name='背膘厚')),
                ('index_quantity', models.FloatField(verbose_name='默认饲喂量')),
                ('algo_quantity', models.FloatField(verbose_name='计算饲喂量')),
                ('set_quantity', models.FloatField(verbose_name='设置饲喂量')),
                ('settime', models.DateField(default='2020-07-09', verbose_name='设置日期')),
            ],
            options={
                'verbose_name': '饲喂量',
                'verbose_name_plural': '饲喂量',
                'db_table': 'tb_foodquantity',
            },
        ),
    ]
