# Generated by Django 3.0.8 on 2020-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='settime',
            field=models.DateField(default='2020-07-10', verbose_name='设置日期'),
        ),
    ]
