# Generated by Django 3.0.8 on 2020-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0002_auto_20200710_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='settime',
            field=models.DateField(default='2020-07-11', verbose_name='设置日期'),
        ),
    ]
