# Generated by Django 3.0.8 on 2020-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0003_auto_20200711_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='settime',
            field=models.DateField(default='2020-07-12', verbose_name='设置日期'),
        ),
    ]
