# Generated by Django 3.0.8 on 2020-07-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0004_auto_20200712_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='algo_quantity',
            field=models.FloatField(default=2, verbose_name='计算饲喂量'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='index_quantity',
            field=models.FloatField(default=1, verbose_name='默认饲喂量'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='set_quantity',
            field=models.FloatField(default=100, verbose_name='设置饲喂量'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='settime',
            field=models.DateField(default='2020-07-13', verbose_name='设置日期'),
        ),
    ]
