# Generated by Django 3.0.8 on 2020-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0005_auto_20200713_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodquantity',
            name='earid',
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='settime',
            field=models.DateField(default='2020-07-15', verbose_name='设置日期'),
        ),
    ]
