# Generated by Django 3.0.8 on 2020-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quantity', '0006_auto_20200715_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodquantity',
            name='algo_quantity',
            field=models.FloatField(null=True, verbose_name='计算饲喂量'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='backfat',
            field=models.CharField(max_length=20, null=True, verbose_name='背膘厚'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='set_quantity',
            field=models.FloatField(null=True, verbose_name='设置饲喂量'),
        ),
    ]
