# Generated by Django 3.0.8 on 2020-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.CharField(max_length=20, verbose_name='饲喂站号')),
                ('status', models.CharField(default='停止', max_length=20, verbose_name='状态')),
                ('temperature', models.FloatField(default=25, verbose_name='温度')),
                ('humidity', models.FloatField(default=0.4, verbose_name='温度')),
                ('statusnum', models.CharField(default=0, max_length=20, verbose_name='状态码')),
            ],
            options={
                'verbose_name': '饲喂站信息',
                'verbose_name_plural': '饲喂站信息',
                'db_table': 'tb_stationinfo',
            },
        ),
    ]
