# Generated by Django 3.0.8 on 2020-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='roomid',
            field=models.SmallIntegerField(default=1, verbose_name='单元号'),
            preserve_default=False,
        ),
    ]
