# Generated by Django 3.0.8 on 2020-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_stationinfo_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationinfo',
            name='roomid',
        ),
        migrations.RemoveField(
            model_name='stationinfo',
            name='stationid',
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='room_station',
            field=models.CharField(default=1, max_length=8, verbose_name='单元号'),
            preserve_default=False,
        ),
    ]
