# Generated by Django 3.0.8 on 2020-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20200710_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationinfo',
            old_name='statusnum',
            new_name='status_num',
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='status',
            field=models.CharField(default='已关机', max_length=20, verbose_name='状态'),
        ),
    ]
