# Generated by Django 3.0.8 on 2020-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PigBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.CharField(default=0, max_length=20, verbose_name='饲喂站号')),
                ('pigid', models.IntegerField(verbose_name='身份码')),
                ('earid', models.IntegerField(verbose_name='耳标号')),
                ('pigkind', models.CharField(max_length=20, null=True, verbose_name='品种')),
                ('malepignum', models.CharField(max_length=20, verbose_name='与配公猪号')),
                ('gesage', models.IntegerField(default=0, verbose_name='胎龄')),
                ('vaccine', models.CharField(max_length=64, verbose_name='疫苗情况')),
                ('addpigtime', models.DateField(default='2020-07-12', verbose_name='入栏日期')),
                ('breedtime', models.CharField(default=0, max_length=20, verbose_name='配种日期')),
                ('decpigtime', models.DateField(max_length=20, null=True, verbose_name='出栏日期')),
            ],
            options={
                'verbose_name': '动物基础表',
                'db_table': 'tb_pigbase',
            },
        ),
    ]
