# Generated by Django 3.0.8 on 2020-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pig_base', '0002_auto_20200713_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigbase',
            name='gesage',
            field=models.FloatField(default=0, verbose_name='胎龄'),
        ),
    ]
