# Generated by Django 3.0.8 on 2020-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pig_base', '0003_auto_20200713_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigbase',
            name='addpigtime',
            field=models.DateField(default='2020-07-15', verbose_name='入栏日期'),
        ),
    ]
