# Generated by Django 3.0.8 on 2020-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pig_base', '0004_auto_20200715_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigbase',
            name='addpigtime',
            field=models.DateField(default='2020-07-16', verbose_name='入栏日期'),
        ),
        migrations.AlterField(
            model_name='pigbase',
            name='earid',
            field=models.CharField(max_length=16, verbose_name='耳标号'),
        ),
        migrations.AlterField(
            model_name='pigbase',
            name='pigid',
            field=models.CharField(max_length=16, verbose_name='身份码'),
        ),
    ]
